

#TARGET_DIR = ../bin/

TARGET =	$(TARGET_DIR)lib$(LAST_DIR).so


include ../../common.mk

test:
	@printf "CXX: %s\n" $(CXX)
	@printf "obj: %s\n" $(OBJ)
	@printf "CXXFLAGS: %s\n" $(CXXFLAGS)
	@printf "CPPFLAGS: %s\n" $(CPPFLAGS)
	@printf "LDLIBS: %s\n" $(LDLIBS)
	@printf "LDFLAGS: %s\n" $(LDFLAGS)
	@printf "TARGET: %s\n" $(TARGET)
	@printf "dirname: %s\n" $(LAST_DIR)

