

include ../../common-lib.mk


.PHONY: test
test:
	@printf "CXX: %s\n" $(CXX)
	@printf "obj: %s\n" $(OBJ)
	@printf "CXXFLAGS: %s\n" $(CXXFLAGS)
	@printf "CPPFLAGS: %s\n" $(CPPFLAGS)
	@printf "LDLIBS: %s\n" $(LDLIBS)
	@printf "LDFLAGS: %s\n" $(LDFLAGS)
	@printf "TARGET: %s\n" $(TARGET)
	@printf "dirname: %s\n" $(LAST_DIR)
	@printf "DEPS: %s\n" $(DEPS)
