#
#	Necessary packages:
#	===================
#
#		- libcppuint-1.12-1
#		- libcppuint-dev
#


include ../../../common-test.mk


.PHONY: test
test:
	@printf "LIBS: %s\n" $(LIBS)
	@printf "LDLIBS: %s\n" $(LDLIBS)
	@printf "LDFLAGS: %s\n" $(LDFLAGS)
	@printf "TARGET: %s\n" $(TARGET)
	@printf "INC: %s\n" $(INC)
	@printf "DEPS: %s\n" $(DEPS)
